### ISSUE TITLE
Missing award ids in programs

### ISSUE THREAD

**Issue by paddlesports-north-america** [paddlesports-north-america/pna-site#28]
Listed below are a number of Programs in the database do not have an associated award. I suspect this is incorrect as it makes it the case that completing, say, 4 star sea training, will not automatically create a Qualification for the member.

I suspect this is simply an oversight and in most cases it looks trivial to resolve. Is there any reason to not update the (obviously correct) programs with the relevant award?

"Paddlesport Start"
"4 Star Sea Training"
"4 Star Canoe Training"
"4 Star White Water Training"
"4 Star Surf Training"
"5 Star Sea Training"
"5 Star Canoe Training"
"5 Star White Water Training"
"5 Star Surf Training"
"Coach Level 2 Training"
"Moderate Water Sea Training"
"Moderate Water Canoe Training"
"Moderate Water White Water Training"
"Moderate Water Surf Training"
"Coach Level 3 Generic Core Training"
"Coach Level 3 Sea Training"
"Coach Level 3 Canoe Training"
"Coach Level 3 White Water Training"
"Coach Level 3 Surf Training"
"Advanced Water Sea Training"
"Advanced Water Canoe Training"
"Advanced Water White Water Training"
"Advanced Water Surf Training"
"3 Star Sea Training"
"3 Star Open Canoe Training"
"3 Star Whitewater Training"
"4 Star Sea Training"
"FSRT Provider Orientation"
"Level 1 Online Moderation"
"level 2 Online Moderation"
"Coach Educator Moderation Level 1 & 2"

**Comment by sfairty** [comment]
There are no awards associated with trainings.  Trainings get recorded in an individual's db record when they are entered into the "manage students" field of the course.  No certificates are issued for any trainings.  I do send a letter confirming participation for  Leader and Advanced Leader trainings.

Paddlesport Star should be the only one in the list that probably needs an award associated with it.

**Comment by paddlesports-north-america** [comment]
You're correct of course. However the system is not strictly modeled along operational lines. If you go to the members page you are given the option to filter by qualification ("HAS QUALIFICATIONS"). The values presented are the list of awards available in the system. 

One of the first qualifications you'll see is 2 Star Training. If you select and filter on that value you will retrieve no records. This is because the 2 Star Training program is not associated with the 2 Star Training award. 

Thinking a bit more about it I think I was wrong to suggest adding the awards to the programs that don't have them. I'll delete the awards (e.g. 2 Star Training) that are not associated with a program. This probably points out a need to create a query that gives all members that have participated in a particular program, something you cannot easily find right now.

**Comment by sfairty** [comment]
There wouldn't be anyone in the DB with 2 star training as it is only there so a course can be listed on the calendar.  There is nothing recorded in the db following a 1,2, or 3 star training. 

Having additional queries would be helpful.

**Comment by paddlesports-north-america** [comment]
Resolved in master with 18515f1
