### ISSUE TITLE
error when sorting

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna-site#38]
Getting a "something went wrong" error when trying to sort from the Courses main page and sorting by Course Director.

**Comment by rkitts** [comment]
Please take a look at 

https://pna-dev-pr-39.herokuapp.com/admin/courses

This sorts course providers by LAST name and then displays the entire name of the coach. Let me know if this works and I'll merge and deploy it into production.

**Comment by sfairty** [comment]
That works

Deploy!

**Comment by rkitts** [comment]
Fixed with ebb27488fcc4b3f7d2fdacffbd99afa3f81a6da6
