### ISSUE TITLE
"Center" drop down menu alphabetized

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna-site#48]
On the main "courses" page in the filter pane we have a sort field for "center" can this be alphabetized?

**Comment by rkitts** [comment]
Sorry for the delay, I'm a little busy just now.

It looks like it can be. I'll try to get it done by early next week.

**Comment by rkitts** [comment]
Resolved with commit 17da52a770ca229f91e4a5193b4d5c012ceb8dab
