### ISSUE TITLE
Re-branding of 4 and 5 Star Awards

### ISSUE THREAD

**Issue by ozardjw** [paddlesports-north-america/pna-site#6]
Today (I think) marks the official rebranding date for changing "4 Star Sea Leader" to "Sea Kayak Leader" and "5 Star Sea Leader" to "Advanced Sea Kayak Leader"

The other courses in the db to change would be "4 star sea training" to "sea kayak leader training"

and "5 star sea training" to "advanced sea kayak leader training"

The other 4 star courses (canoe, surf, whitewater) also need to be rebranded but are less critical.

All existing people who hold the "old" award should automatically be rebranded in their db records as well. My db record shows I am a "5 Star Sea Leader"; my updated record should say "Advanced Sea Kayak Leader".

Hope this isn't a giant headache to implement.

**Comment by paddlesports-north-america** [comment]
Should I change "4 Star Sea Provider" and "5 Star Sea Provider" as well?

**Comment by rkitts** [comment]
I don’t think you’re subscribed to this issue Scott.

—Rick

**Comment by sfairty** [comment]
The "subscribe" thing is new to me.

Yes, we also need to change the Provider course names as well.

**Comment by ozardjw** [comment]
Rick,
Yes.

4 Star xxx Provider becomes: Moderate Water Leader Provider. For
example, Moderate
Water Sea Kayak Leader Provider, Moderate Water Canoe Leader Provider, Moderate
Water White Water Kayak Leader Provider, etc.

Same thing for 5 Star xxx: Advanced Water Leader Provider. For
example, Advanced
Water Sea Kayak Leader Provider, Advanced Water Canoe Leader Provider, Advanced
Water White Water Kayak Leader Provider, etc.
John

**Comment by rkitts** [comment]
I want to make sure then that the "4 Star Sea Leader" award should *NOT* then be named "Moderate Water Sea Kayak Leader".

**Comment by ozardjw** [comment]
Rick,
Scott is checking with British Canoeing on the correct title to use for the
former 4 Star and 5 Star Leader Providers. Hope to get back to you in a day
or so.
John

**Comment by ozardjw** [comment]
There is still some conflicting terminology on the BC site concerning the rebranded leadership awards so I asked Karen (BC) for some clarification. The official list of old and new names is attached.

Presumably the word "Provider" is attached after each to designate those coaches that can run training and assessments.
[British Canoeing Leadership Awards Agreed Names.docx](https://github.com/paddlesports-north-america/pna-site/files/893270/British.Canoeing.Leadership.Awards.Agreed.Names.docx)

**Comment by rkitts** [comment]
You closed this issue. Does that mean to not worry about it for now?

**Comment by ozardjw** [comment]
Doh! No, that must have been accidental. I was adding the correct
nomenclature from British Canoeing for the rebranding of 4 and 5 Star
Awards and 4 and 5 Star Providers

**Comment by rkitts** [comment]
I've deployed the changes for this to https://pna-dev-pr-7.herokuapp.com. You can see the results of the change in relevant admin pages. Username and password as they are for the production site. Let me know if you see any problems. If not I'll push the changes to production.

Here are the changes made, where the | symbol means "became.

4 Star Sea Leader | Sea Kayak Leader
4 Star Surf Leader | Surf Kayak Leader
4 Star Canoe Leader | Canoe Leader
4 Star White Water Leader | White Water Kayak Leader
4 Star White Water OC1 Leader | White Water OC1 Leader
5 Star Sea Leader | Advanced Sea Kayak Leader
5 Star Surf Leader | Advanced Surf Kayak Leader
5 Star Canoe Leader | Advanced Canoe Leader
5 Star White Water Leader | Advanced White Water Kayak Leader
5 Star White Water OC1 Leader | Advanced White Water OC1 Leader
4 Star Surf Provider | Surf Kayak Leader Provider
4 Star White Water Provider | White Water Kayak Leader Provider
4 Star Canoe Provider | Canoe Leader Provider
4 Star Sea Provider | Sea Kayak Leader Provider
5 Star Sea Provider | Advanced Sea Kayak Leader Provider
5 Star Canoe Provider | Advanced Canoe Leader Provider
5 Star White Water Provider | Advanced White Water Kayak Leader Provider
5 Star Surf Provider | Advanced Surf Kayak Leader Provider

**Comment by ozardjw** [comment]
Rick,
These look good.

I have a question into Scott about the course names as well. For example, Shawna has a 4 Star Sea Leader Training scheduled for June that shows up on the Calendar as 4 Star Sea Training. We probably want to change those to Sea Kayak Leader Training as well, but we might want to do that by adding a new course name, so that former 4 Star Sea Training remain in the database as historical names. I don't know what Scott thinks we should do with these yet, but will get back to you. 

We will also need to rebrand our documents page and probably change most of the links on that as well, but that is a separate issue!
John
